version: "3.9"
services:
  xui:
    image: ghcr.io/mhsanaei/3x-ui:v2.6.2
    container_name: xui
    volumes:
      - $PWD/db/:/etc/x-ui/
      - $PWD/cert/:/root/cert/
    environment:
      - XRAY_VMESS_AEAD_FORCED=false
    restart: unless-stopped
    network_mode: host
